<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9II2C15" failures="1" tests="1" name="Validate title" time="29.179" errors="0" timestamp="07 Jul 2021 04:51:10 GMT">
  <testcase classname="insurity.ValidateCaption" name="validateTitle" time="0.562">
    <failure type="java.lang.AssertionError" message="expected [/////WHY WEâ€™RE DIFFERENT] but found [WHY WE’RE DIFFERENT]">
      <![CDATA[java.lang.AssertionError: expected [/////WHY WEâ€™RE DIFFERENT] but found [WHY WE’RE DIFFERENT]
at insurity.ValidateCaption.validateTitle(ValidateCaption.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
</testsuite> <!-- Validate title -->
